package spring_boot_learning.sb_learn;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SbLearnApplication {

	public static void main(String[] args) {
		SpringApplication.run(SbLearnApplication.class, args);
	}

}
